[project]
name = "cvitae-saas-backend"
version = "0.1.0"
description = "FastAPI wrapper for CVitae engine"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "python-dotenv>=1.0.0",
    "cvitae",
    "pydantic-i18n",
    "ulid-py>=1.1.0",
    "peewee>=4.3.0",
]

[tool.uv.sources]
cvitae = { path = "../core-engine", editable = true }
